batch_size: 128
clip_duration_ms: 1500
eval_step_interval: 500
features:
- features_dir: generated_augmented_features
  penalty_weight: 1.0
  sampling_weight: 2.5
  truncation_strategy: truncate_start
  truth: true
  type: mmap
- features_dir: negative_datasets/speech
  penalty_weight: 1.0
  sampling_weight: 10.0
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: negative_datasets/dinner_party
  penalty_weight: 1.0
  sampling_weight: 10.0
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: negative_datasets/no_speech
  penalty_weight: 1.0
  sampling_weight: 5.0
  truncation_strategy: random
  truth: false
  type: mmap
- features_dir: negative_datasets/dinner_party_eval
  penalty_weight: 1.0
  sampling_weight: 0.0
  truncation_strategy: split
  truth: false
  type: mmap
flags:
  first_conv_filters: 32
  first_conv_kernel_size: 5
  max_pool: 0
  mixconv_kernel_sizes: '[5], [7,11], [9,15], [23]'
  model_name: mixednet
  pointwise_filters: 64,64,64,64
  pooled: 0
  repeat_in_block: 1, 1, 1, 1
  residual_connection: 0,0,0,0
  restore_checkpoint: 1
  spatial_attention: 0
  stride: 3
  test_tf_nonstreaming: 0
  test_tflite_nonstreaming: 0
  test_tflite_nonstreaming_quantized: 0
  test_tflite_streaming: 0
  test_tflite_streaming_quantized: 1
  train: 1
  training_config: training_parameters.yaml
  use_weights: best_weights
  verbosity: 0
freq_mask_count:
- 0
freq_mask_max_size:
- 0
learning_rates:
- 0.001
maximization_metric: average_viable_recall
minimization_metric: null
negative_class_weight:
- 30
positive_class_weight:
- 1
spectrogram_length: 204
spectrogram_length_final_layer: 50
stride: 3
summaries_dir: trained_models/wakeword/logs/
target_minimization: 0.9
time_mask_count:
- 0
time_mask_max_size:
- 0
train_dir: trained_models/wakeword
training_input_shape: !!python/tuple
- 204
- 40
training_steps:
- 20000
window_step_ms: 10
